### ISSUE TITLE
ImportError: No module named mkm

### ISSUE THREAD

**Issue by dbadia** [cortex/sqrl#6]
Trying to run the client on Debian Jessie but I am getting

dave@jj:~/sqrl$ sqrl "sqrl://example.com/login/sqrl?d=6&nut=a95fa8e88dc499758"
Traceback (most recent call last):
  File "/usr/local/bin/sqrl", line 9, in <module>
    load_entry_point('sqrl==0.0.1', 'console_scripts', 'sqrl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "build/bdist.linux-x86_64/egg/sqrl/sqrl.py", line 20, in <module>
ImportError: No module named mkm

**Comment by alexschrod** [comment]
Getting the same error message on Ubuntu 16.10.

**Comment by gitmayer** [comment]
was this resolved? I'm first time installing and getting the same error.
